### PR TITLE
Medium transformation fixes

### PR DESCRIPTION
**Pull request by dkochmanski**
This is a big change, I'm making a pull request now because it changes a lot already and I don't want to diverge from codebase too much. Changes:

- reversal of non-conforming medium transformation changes
- moving permanent-medium-sheet-output-mixin up to basic-pane
- graphic state recording
- correct handling transformed inks (right now we have software implementation)
- clx-fb and renderer has been rewritten (there might be a performance regression, but it is possible to reintroduce performance improvements on top of the current, less complicated architecture)
- indirect-ink's has been programmed into a protocol based on dynamic variables
- all ink transformations are done now in software - most notably image transformation demo is very slow; fixing it is part of the next iteration I'm working on (rewriting clx to utilize xrener to its fullest)
- rotating patterns
- pattern may have any other ink as one of its designs (including other patterns)
- many more changes I don't remember (what is a great indicator, that it shouldn't be kept in a separate branch any longer)

Some regressions are expected, but IMHO this branch should be merged and after that we should work from there to mitigate them.

### CODE REVIEW

**Comment by nsrahmad** [comment]
I am testing this branch now, so far I am unable to get the examples loaded.
### with SBCL 1.4.11
```lisp
[nsrahmad@archlinux ~]$ sbcl
This is SBCL 1.4.11, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
* (ql:quickload "clim-examples")
To load "clim-examples":
  Load 1 ASDF system:
    clim-examples
; Loading "clim-examples"
..............
;; try (CLIM-DEMO:DEMODEMO)
.
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {10005E85B3}>:
  unknown type specifier: '(SIMPLE-ARRAY (SINGLE-FLOAT 0.0 1.0) 2)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "clim-examples" "patterns">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "clim-examples" "patterns">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "clim-examples"
  7:                                 Exit debugger, returning to top level.

(SB-KERNEL:%%TYPEP #2A((0.0 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 ...) (0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 ...) (0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 ...) (0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 ...) (0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 ...) (0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 ...) (0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 ...) (0.07 0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 ...) (0.08 0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 ...) (0.09 0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ...) (0.1 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 ...) (0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 0.21 0.22 ...) ...) #<SB-KERNEL:UNKNOWN-TYPE (QUOTE (SIMPLE-ARRAY (SINGLE-FLOAT 0.0 1.0) 2))> T)
```
-----
### with CCL 1.11.5
```lisp
[nsrahmad@archlinux ~]$ ccl64
Clozure Common Lisp Version 1.11.5/v1.11.5  (LinuxX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (ql:quickload "clim-examples")
To load "clim-examples":
  Load 1 ASDF system:
    clim-examples
; Loading "clim-examples"
.............................
> Error: The value ARG-LIST is not of the expected type SEQUENCE.
> While executing: CCL::SEQUENCE-TYPE, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > :b
 (7FA76704FAF0) : 0 (SEQUENCE-TYPE ARG-LIST) 197
 (7FA76704FB10) : 1 (LENGTH ARG-LIST) 37
 (7FA76704FB28) : 2 (NX-TRANSFORM (#:|`,@| . ARG-LIST) #<CCL::LEXICAL-ENVIRONMENT #x30200187877D> #<HASH-TABLE :TEST EQ size 2704/3484 #x3020015B9FDD>) 1669
 (7FA76704FBB0) : 3 (NX-TRANSFORM-ARGLIST (MAKE-INSTANCE '# :STREAM STREAM (#:|`,@| . ARG-LIST)) #<CCL::LEXICAL-ENVIRONMENT #x30200187877D> #<HASH-TABLE :TEST EQ size 2704/3484 #x3020015B9FDD>) 213
 (7FA76704FC10) : 4 (NX-TRANSFORM (MAKE-INSTANCE '# :STREAM STREAM (#:|`,@| . ARG-LIST)) #<CCL::LEXICAL-ENVIRONMENT #x30200187877D> #<HASH-TABLE :TEST EQ size 2704/3484 #x3020015B9FDD>) 949
 (7FA76704FCA0) : 5 (NX1-TYPED-FORM :VALUE (MAKE-INSTANCE '# :STREAM STREAM (#:|`,@| . ARG-LIST)) #<CCL::LEXICAL-ENVIRONMENT #x30200187877D>) 101
 (7FA76704FCD8) : 6 (NX1-TYPED-VAR-INITFORM #S(CCL::PENDING-DECLARATIONS :VDECLS NIL :FDECLS NIL ...) RECORD (MAKE-INSTANCE '# :STREAM STREAM (#:|`,@| . ARG-LIST)) #<CCL::LEXICAL-ENVIRONMENT #x30200187877D>) 549
 (7FA76704FD50) : 7 (FUNCALL #'#<CCL::NX1-LET*> NIL (LET* (#) (STREAM-ADD-OUTPUT-RECORD STREAM RECORD)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 669
 (7FA76704FE40) : 8 (NX1-COMBINATION NIL (LET* (#) (STREAM-ADD-OUTPUT-RECORD STREAM RECORD)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 541
 (7FA76704FEA8) : 9 (NX1-TRANSFORMED-FORM NIL (LET* (#) (STREAM-ADD-OUTPUT-RECORD STREAM RECORD)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 325
 (7FA76704FF10) : 10 (NX1-TYPED-FORM NIL (PROGN (LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 253
 (7FA76704FF78) : 11 (NX1-FORM NIL (PROGN (LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 469
 (7FA76704FFF8) : 12 (FUNCALL #'#<CCL::NX1-IF> NIL (IF (STREAM-RECORDING-P STREAM) (PROGN #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 413
 (7FA767050088) : 13 (NX1-COMBINATION NIL (IF (STREAM-RECORDING-P STREAM) (PROGN #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 541
 (7FA7670500F0) : 14 (NX1-TRANSFORMED-FORM NIL (IF (STREAM-RECORDING-P STREAM) (PROGN #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 325
 (7FA767050158) : 15 (NX1-TYPED-FORM NIL (WHEN (STREAM-RECORDING-P STREAM) (LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 253
 (7FA7670501C0) : 16 (NX1-FORM NIL (WHEN (STREAM-RECORDING-P STREAM) (LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 469
 (7FA767050240) : 17 (NX1-PROGN-BODY :RETURN ((WHEN # #) (WHEN # #))) 157
 (7FA767050288) : 18 (NX1-COMBINATION :RETURN (PROGN (WHEN # #) (WHEN # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 541
 (7FA7670502F0) : 19 (NX1-TRANSFORMED-FORM :RETURN (PROGN (WHEN # #) (WHEN # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 325
 (7FA767050358) : 20 (NX1-TYPED-FORM :RETURN (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD (POINT-X POINT-Y)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 253
 (7FA7670503C0) : 21 (NX1-FORM :RETURN (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD (POINT-X POINT-Y)) #<CCL::LEXICAL-ENVIRONMENT #x3020018791ED>) 469
 (7FA767050440) : 22 (NX1-ENV-BODY :RETURN ((GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187923D> NIL) 197
 (7FA767050498) : 23 (FUNCALL #'#<CCL::NX1-FLET> :RETURN (FLET (# #) (DECLARE #) (DECLARE #) (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187940D>) 2373
 (7FA7670505E0) : 24 (NX1-COMBINATION :RETURN (FLET (# #) (DECLARE #) (DECLARE #) (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187940D>) 541
 (7FA767050648) : 25 (NX1-TRANSFORMED-FORM :RETURN (FLET (# #) (DECLARE #) (DECLARE #) (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187940D>) 325
 (7FA7670506B0) : 26 (NX1-TYPED-FORM :RETURN (FLET (# #) (DECLARE #) (DECLARE #) (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187940D>) 253
 (7FA767050718) : 27 (NX1-FORM :RETURN (FLET (# #) (DECLARE #) (DECLARE #) (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187940D>) 469
 (7FA767050798) : 28 (FUNCALL #'#<CCL::NX1-BLOCK> :RETURN (BLOCK MEDIUM-DRAW-POINT* (FLET # # # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018797ED>) 589
 (7FA767050830) : 29 (NX1-COMBINATION :RETURN (BLOCK MEDIUM-DRAW-POINT* (FLET # # # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018797ED>) 541
 (7FA767050898) : 30 (NX1-TRANSFORMED-FORM :RETURN (BLOCK MEDIUM-DRAW-POINT* (FLET # # # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018797ED>) 325
 (7FA767050900) : 31 (NX1-TYPED-FORM :RETURN (BLOCK MEDIUM-DRAW-POINT* (FLET # # # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018797ED>) 253
 (7FA767050968) : 32 (NX1-FORM :RETURN (BLOCK MEDIUM-DRAW-POINT* (FLET # # # #)) #<CCL::LEXICAL-ENVIRONMENT #x3020018797ED>) 469
 (7FA7670509E8) : 33 (NX1-ENV-BODY :RETURN ((BLOCK MEDIUM-DRAW-POINT* #)) #<CCL::LEXICAL-ENVIRONMENT #x30200187989D> NIL) 197
 (7FA767050A40) : 34 (NX1-LAMBDA (STREAM POINT-X POINT-Y) ((BLOCK MEDIUM-DRAW-POINT* #)) ((DECLARE #))) 1445
 (7FA767050B28) : 35 (NX1-COMPILE-LAMBDA (MEDIUM-DRAW-POINT* :AROUND (OUTPUT-RECORDING-STREAM T T)) (LAMBDA (CCL::&METHOD #:NEXT-METHOD-CONTEXT STREAM POINT-X POINT-Y) (DECLARE #) (BLOCK MEDIUM-DRAW-POINT* #)) #<CCL::AFUNC #x3020018798FD> #<CCL::AFUNC #x302001879F1D> #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD> #<CCL:COMPILER-POLICY #x30200025D54D> #:LOAD-TIME-EVAL) 2269
 (7FA767050DF8) : 36 (NX1-REF-INNER-FUNCTION MEDIUM-DRAW-POINT* (LAMBDA (CCL::&METHOD #:NEXT-METHOD-CONTEXT STREAM POINT-X POINT-Y) (DECLARE #) (BLOCK MEDIUM-DRAW-POINT* #)) NIL) 69
 (7FA767050E20) : 37 (NX1-COMBINATION :VALUE (CCL:NFUNCTION MEDIUM-DRAW-POINT* (LAMBDA # # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 541
 (7FA767050E88) : 38 (NX1-TRANSFORMED-FORM :VALUE (CCL:NFUNCTION MEDIUM-DRAW-POINT* (LAMBDA # # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 325
 (7FA767050EF0) : 39 (NX1-TYPED-FORM :VALUE (CCL:NFUNCTION MEDIUM-DRAW-POINT* (LAMBDA # # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 253
 (7FA767050F58) : 40 (NX1-FORM :VALUE (CCL:NFUNCTION MEDIUM-DRAW-POINT* (LAMBDA # # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 469
 (7FA767050FD8) : 41 (NX1-ARGLIST ((CCL:NFUNCTION MEDIUM-DRAW-POINT* #) :QUALIFIERS '# :LAMBDA-LIST '#) 3) 261
 (7FA767051028) : 42 (NX1-CALL-FORM :VALUE CCL::ENSURE-METHOD NIL ('MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) :QUALIFIERS ...) NIL #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 1509
 (7FA7670510B0) : 43 (NX1-CALL :VALUE CCL::ENSURE-METHOD ('MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) :QUALIFIERS ...) NIL NIL NIL) 1669
 (7FA767051140) : 44 (NX1-TYPED-CALL :VALUE CCL::ENSURE-METHOD ('MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) :QUALIFIERS ...) NIL) 509
 (7FA767051190) : 45 (NX1-COMBINATION :VALUE (CCL::ENSURE-METHOD 'MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) ...) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 637
 (7FA7670511F8) : 46 (NX1-TRANSFORMED-FORM :VALUE (CCL::ENSURE-METHOD 'MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) ...) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 325
 (7FA767051260) : 47 (NX1-TYPED-FORM :VALUE (CCL::ENSURE-METHOD 'MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) ...) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 253
 (7FA7670512C8) : 48 (NX1-TYPED-VAR-INITFORM #S(CCL::PENDING-DECLARATIONS :VDECLS NIL :FDECLS NIL ...) #:G2722 (CCL::ENSURE-METHOD 'MEDIUM-DRAW-POINT* (LIST # T T) :FUNCTION (CCL:NFUNCTION MEDIUM-DRAW-POINT* #) ...) #<CCL::LEXICAL-ENVIRONMENT #x302001879DAD>) 549
 (7FA767051340) : 49 (FUNCALL #'#<CCL::NX1-LET*> :RETURN (LET* (#) (CCL:RECORD-SOURCE-FILE #:G2722 #) #:G2722) #<CCL::LEXICAL-ENVIRONMENT #x302001879E4D>) 669
 (7FA767051430) : 50 (NX1-COMBINATION :RETURN (LET* (#) (CCL:RECORD-SOURCE-FILE #:G2722 #) #:G2722) #<CCL::LEXICAL-ENVIRONMENT #x302001879E4D>) 541
 (7FA767051498) : 51 (NX1-TRANSFORMED-FORM :RETURN (LET* (#) (CCL:RECORD-SOURCE-FILE #:G2722 #) #:G2722) #<CCL::LEXICAL-ENVIRONMENT #x302001879E4D>) 325
 (7FA767051500) : 52 (NX1-TYPED-FORM :RETURN (PROGN (LET* # # #:G2722)) #<CCL::LEXICAL-ENVIRONMENT #x302001879E4D>) 253
 (7FA767051568) : 53 (NX1-FORM :RETURN (PROGN (LET* # # #:G2722)) #<CCL::LEXICAL-ENVIRONMENT #x302001879E4D>) 469
 (7FA7670515E8) : 54 (NX1-ENV-BODY :RETURN ((PROGN #)) #<CCL::LEXICAL-ENVIRONMENT #x302001879ECD> NIL) 197
 (7FA767051640) : 55 (NX1-LAMBDA NIL ((PROGN #)) NIL) 1445
 (7FA767051728) : 56 (NX1-COMPILE-LAMBDA NIL (LAMBDA NIL (PROGN #)) #<CCL::AFUNC #x302001879F1D> NIL #<CCL::LEXICAL-ENVIRONMENT #x302001879FED> #<CCL:COMPILER-POLICY #x30200025D54D> #:LOAD-TIME-EVAL) 2269
 (7FA7670519F8) : 57 (COMPILE-NAMED-FUNCTION (LAMBDA NIL (PROGN #)) :NAME NIL :ENV #<CCL::LEXICAL-ENVIRONMENT #x30200187A03D> :POLICY #<CCL:COMPILER-POLICY #x30200025D54D> :LOAD-TIME-EVAL-TOKEN #:LOAD-TIME-EVAL :TARGET :LINUXX8664 :FUNCTION-NOTE NIL :KEEP-LAMBDA NIL :KEEP-SYMBOLS T :SOURCE-NOTES #<HASH-TABLE :TEST EQ size 2704/3484 #x3020015B9FDD> :RECORD-PC-MAPPING T :COMPILE-CODE-COVERAGE NIL) 1781
 (7FA767051BF0) : 58 (FCOMP-NAMED-FUNCTION (LAMBDA NIL (PROGN #)) NIL #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> NIL) 525
 (7FA767051C58) : 59 (FCOMP-COMPILE-TOPLEVEL-FORMS #<CCL::LEXICAL-ENVIRONMENT #x302001594CED>) 701
 (7FA767051CF8) : 60 (FCOMP-COMPILER-LET (CCL:COMPILER-LET (#) (LET* # # #:G2722)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 581
 (7FA767051D50) : 61 (FCOMP-FORM (CCL:COMPILER-LET (#) (LET* # # #:G2722)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 1981
 (7FA767051DE0) : 62 (FCOMP-FORM-LIST ((EVAL-WHEN # #) (CCL:COMPILER-LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 173
 (7FA767051E28) : 63 (FCOMP-FORM (PROGN (EVAL-WHEN # #) (CCL:COMPILER-LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 1981
 (7FA767051EB8) : 64 (FCOMP-FORM (DEFMETHOD MEDIUM-DRAW-POINT* :AROUND (# POINT-X POINT-Y) (GENERATE-MEDIUM-RECORDING-BODY DRAW-POINT-OUTPUT-RECORD #)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 1981
 (7FA767051F48) : 65 (FCOMP-FORM-LIST ((DEFCLASS DRAW-POINT-OUTPUT-RECORD # #) (DEFMETHOD INITIALIZE-INSTANCE :AFTER # #) (DEFMETHOD MEDIUM-DRAW-POINT* :AROUND # #) (DEFMETHOD REPLAY-OUTPUT-RECORD # # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 173
 (7FA767051F90) : 66 (FCOMP-FORM (PROGN (DEFCLASS DRAW-POINT-OUTPUT-RECORD # #) (DEFMETHOD INITIALIZE-INSTANCE :AFTER # #) (DEFMETHOD MEDIUM-DRAW-POINT* :AROUND # #) (DEFMETHOD REPLAY-OUTPUT-RECORD # # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 1981
 (7FA767052020) : 67 (FCOMP-FORM (DEF-GRECORDING DRAW-POINT (# POINT-X POINT-Y) NIL (LET # #)) #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 1981
 (7FA7670520B0) : 68 (FCOMP-READ-LOOP "/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lisp" "home:common-lisp;McCLIM;Core;clim-basic;recording.lisp.newest" 0 #<CCL::LEXICAL-ENVIRONMENT #x302001594CED> :NOT-COMPILE-TIME) 2381
 (7FA767052250) : 69 (FCOMP-FILE "/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lisp" "home:common-lisp;McCLIM;Core;clim-basic;recording.lisp.newest" 0 #<CCL::LEXICAL-ENVIRONMENT #x302001594CED>) 821
 (7FA7670523F0) : 70 (%COMPILE-FILE "/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lisp" "/home/nsrahmad/.cache/common-lisp/ccl-1.11-f96-linux-x64/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording-TMP.lx64fsl" NIL NIL T T NIL T :DEFER NIL #<BACKEND LINUXX8664 #x3020001C707D> :UTF-8 NIL 0) 2333
 (7FA7670526D8) : 71 (COMPILE-FILE #P"/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lisp" :OUTPUT-FILE #P"/home/nsrahmad/.cache/common-lisp/ccl-1.11-f96-linux-x64/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording-TMP.lx64fsl" :VERBOSE NIL :PRINT NIL :LOAD NIL :FEATURES NIL :TARGET :LINUXX8664 :SAVE-LOCAL-SYMBOLS T :SAVE-DOC-STRINGS T :SAVE-DEFINITIONS NIL :SAVE-SOURCE-LOCATIONS T :EXTERNAL-FORMAT :UTF-8 :FORCE NIL :COMPILE-FILE-ORIGINAL-TRUENAME NIL :COMPILE-FILE-ORIGINAL-BUFFER-OFFSET 0 :BREAK-ON-PROGRAM-ERRORS :DEFER :LOAD-PRESERVES-OPTIMIZATION-SETTINGS NIL) 1997
 (7FA767052860) : 72 (CALL-WITH-MUFFLED-CONDITIONS #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL UIOP/LISP-BUILD:COMPILE-FILE*) #x30200159545F> NIL) 389
 (7FA7670528B0) : 73 (CALL-WITH-ENOUGH-PATHNAME #P"/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lisp" NIL #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL UIOP/LISP-BUILD:COMPILE-FILE*) #x3020015954AF>) 189
 (7FA767052908) : 74 (COMPILE-FILE* #P"/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lisp" :OUTPUT-FILE #P"/home/nsrahmad/.cache/common-lisp/ccl-1.11-f96-linux-x64/home/nsrahmad/common-lisp/McCLIM/Core/clim-basic/recording.lx64fsl" :EXTERNAL-FORMAT :UTF-8 :WARNINGS-FILE NIL) 517
 (7FA767052988) : 75 (FUNCALL #<CCL:COMPILED-LEXICAL-CLOSURE (:INTERNAL ASDF/LISP-ACTION:PERFORM-LISP-COMPILATION) #x3020015956DF>) 149
 (7FA7670529B8) : 76 (PERFORM-LISP-COMPILATION #<COMPILE-OP > #<CL-SOURCE-FILE "clim-basic" "recording">) 389
 (7FA767052A08) : 77 (%%BEFORE-AND-AFTER-COMBINED-METHOD-DCODE (NIL #<STANDARD-METHOD ASDF/ACTION:PERFORM #> . 17544620582234)) 845
 (7FA767052A78) : 78 (%%STANDARD-COMBINED-METHOD-DCODE ((#<#>) (#<#>) #<STANDARD-METHOD ASDF/ACTION:PERFORM #>) 17544620582234) 261
```

**Comment by dkochmanski** [comment]
Thanks. Both problems didn't show up in my environment (older sbcl and ecl). They should be fixed now. I've succesfully run clim-demo with ccl (I don't have newest sbcl to check it). First problem was spurious quote in :type initarg for slot, second one was nested backquoting.

**Comment by nsrahmad** [comment]
Okay, It loads fine now. Now some regressions
1) Run either `D&D Translator` or `German Towns` example, Try to highlight any presentation and Note the output in pointer documentation pane.

**Comment by dkochmanski** [comment]
this was a result of introducing indirect-ink protocol as something tangible. should be fixed now (see commit for details).

**Pull request merged**
