### PR TITLE
Add (:menu-bar nil) to demos and tests that don't have menu bars.

### PR DESCRIPTION
**Pull request by duuqnd**
Relevant issue: #912

### CODE REVIEW

**Comment by nsrahmad** [comment]
Hi, good work so far. This Fix misses tests in third column of `demodemo` such as `coordinate-swizzling.lisp`, `flipping-ink.lisp` etc.

**Comment by duuqnd** [comment]
That was intentional. Those are labelled in the demo list as "regression tests", so I thought that a change that's merely cosmetic would not be worth adding to them. I could do it anyway if you think I should.

**Comment by nsrahmad** [comment]
Please do it. It is harmless precisely because "it is merely cosmetic".

**Comment by duuqnd** [comment]
Alright, I've added it the the regression tests too.

**Comment by nsrahmad** [comment]
merged, Thank you.
I wanted to tell you about commit messages. See my edited commit message in https://github.com/McCLIM/McCLIM/commit/a98d3e884dbce35faa91bd36d529db1e92cfda0f 

Your commit message had a single line showing "What" but not "Why". GIT allows much larger text  after the single line message which should be used to describe "Why". (For this reason, I always commit in Magit). Also on Github, if you include a line like "Fixes #912", Github will close that issue automatically after merge.

**Comment by duuqnd** [comment]
Thanks! I'll keep that in mind in the future.

**Pull request merged**
