### PR TITLE
remove clim-postscript::*transformation*

### PR DESCRIPTION
**Pull request by slyrus**

### CODE REVIEW

**Comment by nsrahmad** [comment]
when running `(clim-demo::postscript-test)`, Output on page 6 of ps-test.ps is wrong.

**Comment by slyrus** [comment]
What's wrong with the output on page 6? Looks as specified to me.

**Comment by slyrus** [comment]
The old output was wrong as the with-scaling 50 was a no-op.

**Comment by slyrus** [comment]
@nsrahmad see https://github.com/McCLIM/McCLIM/pull/525 I think both it and this PR should be merged.

**Comment by nsrahmad** [comment]
Merging It now, I wrongly assumed master's output was correct.

**Pull request merged**
