### PR TITLE
handle-repaint: add guarding for empty output-records

### PR DESCRIPTION
**Pull request by dkochmanski**
We are not interested in repainting empty output records. Also we add
check-type in draw-glyphs to ensure early error report (which was
ignored previously for low debug/safety settings). Issue identified
and fix drafted by @jdz.

### CODE REVIEW

**Comment by dkochmanski** [comment]
I'm marking it as wip because I still need to understand, where these empty OR come from (and why there are no non-empty OR at said invalid coordinates)

**Comment by dkochmanski** [comment]
last commit also fixes whitespaces on repaint.lisp so when reviewing it is advised to use "hide whitespace changes".

**Comment by nsrahmad** [comment]
`Coordinate-swizzling` demo failes with:
```lisp
The value of MCCLIM-TRUETYPE::Y is 32783, which is not of type (SIGNED-BYTE
                                                                16).
   [Condition of type SIMPLE-TYPE-ERROR]

Restarts:
 0: [STORE-VALUE] Supply a new value for MCCLIM-TRUETYPE::Y.
 1: [TRY-AGAIN] Try executing the command CLIM-DEMO::COM-FILL again.
 2: [ABORT] Return to application command loop.
 3: [ABORT] Return to application command loop.
 4: [RETRY] Retry SLIME REPL evaluation request.
 5: [*ABORT] Return to SLIME's top level.
 --more--

Backtrace:
  0: (SB-KERNEL:CHECK-TYPE-ERROR MCCLIM-TRUETYPE::Y 32783 (SIGNED-BYTE 16) NIL)
  1: (MCCLIM-FONT:DRAW-GLYPHS #<unavailable argument> #<XLIB:WINDOW :0 200245> #<XLIB:GCONTEXT :0 2097740> 0 #<unavailable argument> "1791" :START #<unavailable argument> :END #<unavailable argument> :TRAN..
  2: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*))
  3: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
  4: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CLIM:MEDIUM-DRAW-TEXT*) {7F10D073EF3B}> #<SB-THREAD:MUTEX "draw-font" owner: #<SB-THREAD:THREAD "repl-thread" RUNNING {1004A..
  5: ((:METHOD CLIM:MEDIUM-DRAW-TEXT* (CLIM-CLX:CLX-RENDER-MEDIUM T T T T T T T T T T)) #<CLIM-CLX:CLX-RENDER-MEDIUM {1003531CE3}> "1791" 0 33569483/1024 0 NIL :LEFT :BASELINE #<unused argument> #<unused a..
 ```

**Comment by dkochmanski** [comment]
Thank you. That's good, change revealed previously unnoticed defect (it is not a regression). I'll look into that soon.

**Comment by dkochmanski** [comment]
I've pushed to this branch. Making drawing not to go outside X coordinates in case of coordinate swizzling is not easy, but that shouldn't not prevent other fixes to get merged. To not bury again this uncovered issue I've put a warning (instead of error) in draw-glyphs.

**Comment by dkochmanski** [comment]
since there are no objections I'm merging it.

**Pull request merged**
