### PR TITLE
Examples/puzzle.lisp: no longer uses non exported symbols

### PR DESCRIPTION
**Pull request by josrr**
I got rid of climi::convert-from-relative-to-absolute-coordinates

### CODE REVIEW

**Comment by josrr** [comment]
Yes I agree; In fact, what you propose is what I did first, but the call to `climi::convert-from-relative-to-absolute-coordinates` confused me a bit.

**Comment by josrr** [comment]
./Apps/Scigraph/dwim/present.lisp uses climi::convert-from-relative-to-absolute-coordinates; so I think we cannot get rid of it.

**Comment by nsrahmad** [comment]
That file uses it exactly in this fashion, I will say go ahead and update that file too. If you do not feel like it then I will do that.

**Comment by josrr** [comment]
OK, I will update that file.

**Comment by josrr** [comment]
The specification mentions the function.

http://bauhh.dyndns.org:8000/clim-spec/edit/apropos?q=redisplay-output-record

**Comment by nsrahmad** [comment]
That's under the `implementation-note` and not actually part of the spec. In McCLIM that function always returns two zeroes and not really useful for anything.

For now, leave that one out.

**Comment by nsrahmad** [comment]
Looks good, Thank you for your work. It made McCLIM better.

**Pull request merged**
