### PR TITLE
Pay attention to the :echo option to with-input-context

### PR DESCRIPTION
**Pull request by heshrobe**
This fixes a minor bug in /Core/clim-core/commands/processor.lisp in the accept presentation method for command.

The method uses with-input-context, but doesn't bind options nor check whether :echo nil is present in options.  If :echo nil is specified (usually from a presentation-translator) then the input should not be placed into the stream.  The fix is shown below (eliding the non-relevant part):

 (flet ((maybe-replace-input (input options)
             (when start-position
               ;; Rescan is nil in case the clicked on thing returned
               ;; something unparseable. -- heshrobe 2020-05-15
               (when (getf options :echo t)
                 (presentation-replace-input stream input type view
                                             :buffer-start start-position
                                             :rescan nil)))
             input)
             ...
      (with-input-context (type)
          (object type event options)
          (if-let ((command (funcall *command-parser* command-table stream)))
            (values (maybe-replace-input (handle-command command) nil) type)
            (simple-parse-error "Empty command"))
        (command
         (values (maybe-replace-input (handle-command object) options) type))))))

### CODE REVIEW

**Comment by scymtym** [comment]
I believe #1072 already addresses this issue.

**Comment by heshrobe** [comment]
Jan,

You’re correct, sorry for not noticing that. 

> On Oct 16, 2020, at 14:35, Jan Moringen <notifications@github.com> wrote:
> 
> 
> I believe #1072 already addresses this issue.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Howard Shrobe

Principal Research Scientist and
Director CyberSecurity@CSAIL
MIT Computer Science and Artificial Intelligence Laboratory
hes@csail.mit.edu
617-253-7877 work
617-312-6439 cell

**Comment by scymtym** [comment]
> You’re correct, sorry for not noticing that.

No worries. Thanks for helping with open issues.

**Comment by dkochmanski** [comment]
I'm closing this duplicated PR. For the record, in this PR the `present` method was removed instead of the (next top level form) `accept` method.

**Pull request closed without merging**
