### PR TITLE
Scigraph dialogs

### PR DESCRIPTION
**Pull request by admich**
With this PR the Scigraph dialogs works and now it is possible to change the line type and the symbol of the data with dialogs.

This solve issue #704 

To try it:
1. load scigraph
2. open scigraph demo `(gr:make-demo-frame)` 
3. right click on one of the two data presentation on the legend of the graph and choose from the menu "Change Data Symbols..."

For the moment in the dialog the line types are printed as number and not graphically as expected from Scigraph code. To improve this it will be necessary in the future:
1. Use `:printer` option of completion presentation in `accept-present-default` methods.
2.  Implement the possibiliy to have for gadget labels not only string but also graphics (pixmap for examples)

### CODE REVIEW

**Comment by slyrus** [comment]
Paraphrasing @dkochmanski , there are a few things going on here:

1. encapsulating-streams fixes
2. CLIM 2.2 feature implementation
3. scigraph cleanup

I'd prefer to see these split up into separate PRs/commits. The encapsulating-stream stuff seems pretty non-controversial, although it suggests that we might want to be a bit more systematic about making sure that the protocol specified in C.1.1 is fully supported.

I don't have a strong opinion about the CLIM 2.2 stuff, but others may.

And I'm all for the scigraph cleanup, subject to the above.

Finally, yet it's a trivial function, but we probably should just re-write highlight-completion-choice instead of slurping it in from the CLIM-TOS stuff.

**Comment by dkochmanski** [comment]
I think you mean @scymtym. I do agree, that this PR should be split in three PRs.

As of copying CLIM-TOS code, I see no problem with that (unless there are technical issues or we could benefit from such rewrite) - licenses are compatible this way.

Regarding CLIM 2.2 incorporation, before we start having these options we could have a chapter in the manual which lists differences from the CLIM 2.0 specification.

**Comment by admich** [comment]
Following yours suggestions, I will close this PR and I will open three different PRs.

**Comment by slyrus** [comment]
Ah, right @scymtym made those suggestions. @admich thanks for breaking this up. Looking forward to seeing the other PRs.

**Pull request closed without merging**
