### PR TITLE
[wip] seos: now queueing operations

### PR DESCRIPTION
**Pull request by g--o**
#585

### CODE REVIEW

**Comment by dkochmanski** [comment]
it doesn't seem to be a complete pull request neither it does follow the approach I've proposed (to queue operations only when they are not executed in clim loop).

regarding copyright headers: changes are too small to add your name to file copyright. Also full names are to be put there (not initials), if you put initials who is the copyright owner?

**Comment by g--o** [comment]
@dkochmanski it doesn't involve the approach you've proposed becaue that approach does not work.
The problem is with draw-text and move-sheet, or more generally rendering and scrolling, so the operations of the stream should be queued on a high level where the logic is clear.

As of the copyright notice I just followed the LGPL template as copying the code should involve getting in contact with whoever made anything there. once the diff becomes empty, names can be removed. How to identify the owner? simply corresponds to the email owner.

**Comment by dkochmanski** [comment]
Saying that it "didn't work" is too vague, could you elaborate why it didn't work? Also there is no need to queue operations if they are invoked from the same thread, it is a waste performance-wise.

Speaking of copyrights, it is a good practice to add them only when significant changes are made, otherwise we'd have longer headers than the source code content. If you implement safe variants for draw-* in graphics that will be surely enough to put the name as a copyright notice.

**Comment by g--o** [comment]
@dkochmanski Oh you mean checking if the stream is running in clim's thread? I'll try that
I honestly didn't agree with your analysis to begin with as the problem didn't exactly seem to stem from draw-rectangle. The draw-rectangle seemed to be invoked from the scrollbar (which is a "side-effect"), meaning: keeping the draw-rectangle but not scrolling works. Trying to queue each and every side effect separately makes little sense when the logical error is trying to render while you scroll.

As of the copyright stuff, look at the end of the day it's your repo (at least partially as a maintainer), i'm just trying to explain that this good practice makes no sense because while harder to maintain the list (e.g: removing names), it makes no clean cut and also asks to give up rights, which i get isn't impressive, but i'm supporting this side for correctness sake.

**Comment by dkochmanski** [comment]
I think that you misunderstand the issue #585. Failure case shown in a #315 is just an example of things going awry; the ticket is about making all asynchronous drawing-related requests (like drawing a circle, a rectangle, printing a text) to the output stream work correctly. While it won't buy much for panes with a display time synchronized with a command loop it will be very useful for panes which are not redisplayed unless explicitly asked. I'm not insisting on a solution with queuing, if you have something better i'm all for it, but please remember that fixing #315 is not this task objective.

**Comment by g--o** [comment]
@dkochmanski huh? the title is "make seos access thread-safe"
the description is 
"Right now when we write asynchronously to a stream output records get corrupted. Issue is reported here:#315"

Are you joking?

**Comment by dkochmanski** [comment]
The problem is caused by output record corruption and issue #315 exhibits the problem. But the issue is deeper than just drawing text. I thought I've explained it in this comment (which was prompted by your question):
https://github.com/McCLIM/McCLIM/issues/585#issuecomment-522527288
As you can probably guess I am not joking.

**Comment by g--o** [comment]
The comment you quoted literally explains nothing. You wanted seos to be thread safe. it is thread safe, plus i checked your hypothesis relevancy. I seriously don't see the problem

**Comment by dkochmanski** [comment]
I won't accept this pull request as a solution for #585. I'm sorry if a lacking description caused you to spend time on something else.

**Comment by g--o** [comment]
wow this is sad, im out

**Pull request closed without merging**
